Repository Dialosoft/backend, pull requests merged in 2024-08, with the labels that each got.

#9 Feature/user service
  .gitignore
  src/user-service/Dockerfile
  src/user-service/go.mod
  src/user-service/go.sum
  src/user-service/go.work
  src/user-service/go.work.sum
  src/user-service/main.go
  src/user-service/src/adapters/controllers/userController.go
  src/user-service/src/adapters/repositories/userRepo.go
  src/user-service/src/adapters/repositories/userRepoImpl.go
  src/user-service/src/adapters/router/router.go
  src/user-service/src/application/services/userService.go
  src/user-service/src/application/services/userServiceImpl.go
  src/user-service/src/domain/entities/request/request.go
  src/user-service/src/domain/entities/response/response.go
  src/user-service/src/domain/entities/roles.go
  src/user-service/src/domain/entities/user.go
  src/user-service/src/domain/ports/userRepository.go
  src/user-service/src/domain/ports/userService.go
  src/user-service/src/infraestructure/db/Dockerfile
  src/user-service/src/infraestructure/db/db.go
  src/user-service/src/infraestructure/logging/logger.go
  src/user-service/src/infraestructure/middlewares/auth.go
Labels: enhancement

#10 refactor: move docker-compose.yml to root and do little changes over …
  docker-compose.yml
  example.env
  src/auth-service/build.gradle
  src/auth-service/src/main/resources/application.yml
  src/auth-service/src/test/java/com/biznetbb/auth/AuthApplicationTests.java
  src/auth-service/src/test/resources/application-test.yml
  src/gateway-service/build.gradle
  src/gateway-service/src/main/resources/application.yml
Labels: bug, enhancement

#11 refactor: add .env file to docker-compose.yml
  docker-compose.yml
Labels: bug

#13 Config/integration compose user service
  docker-compose.yml
  example.env
  src/auth-service/src/main/java/com/biznetbb/auth/web/config/jwt/JwtUtil.java
  src/gateway-service/src/main/resources/application.yml
  src/user-service/Dockerfile
  src/user-service/main.go
  src/user-service/src/adapters/router/router.go
  src/user-service/src/infraestructure/db/db.go
  src/user-service/src/infraestructure/middlewares/auth.go
  src/user-service/src/infraestructure/registry/eureka.go
Labels: bug, enhancement

#19 Feature: Add swagger to auth and gateway services
  docker-compose.yml
  docs/setup-dev.md
  example.env
  src/auth-service/build.gradle
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/CorsConfig.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/OpenApiConfig.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/SecurityConfig.java
  src/auth-service/src/main/resources/application-docker.yml
  src/auth-service/src/main/resources/application-local.yml
  src/auth-service/src/main/resources/application.yml
  src/gateway-service/build.gradle
  src/gateway-service/src/main/java/com/dialosoft/gateway/GatewayApplication.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/WebClientService.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/openapi/SwaggerRoutesConfig.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/openapi/util/SwaggerProperties.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/filter/NonSpringServicesRoutingFilter.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/util/RouterValidator.java
  src/gateway-service/src/main/resources/application.yml
Labels: documentation, enhancement

#21 Feature/get user info
  src/user-service/main.go
  src/user-service/src/adapters/controllers/userController.go
  src/user-service/src/adapters/router/router.go
  src/user-service/src/application/services/userService.go
  src/user-service/src/application/services/userServiceImpl.go
  src/user-service/src/domain/entities/simpleUser.go
Labels: enhancement

#22 Feature: Post manager service, dockerization and swagger
  docker-compose.yml
  src/auth-service/src/main/java/com/dialosoft/auth/persistence/entity/RoleEntity.java
  src/auth-service/src/main/java/com/dialosoft/auth/persistence/entity/UserEntity.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/AuthService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/RefreshTokenService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/UserSecurityService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/utils/RoleInitializer.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/utils/RoleType.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/jwt/JwtUtil.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/filter/RoleBasedAuthorizationFilter.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/util/AuthUtils.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/util/JwtUtils.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/util/RoleType.java
  src/gateway-service/src/main/resources/application.yml
  src/notification-service/HELP.md
  src/post-manager-service/.dockerignore
  src/post-manager-service/.gitignore
  src/post-manager-service/Dockerfile
  src/post-manager-service/build.gradle
  src/post-manager-service/gradle.properties
  src/post-manager-service/gradle/wrapper/gradle-wrapper.jar
  src/post-manager-service/gradle/wrapper/gradle-wrapper.properties
  src/post-manager-service/gradlew
  src/post-manager-service/gradlew.bat
  src/post-manager-service/settings.gradle
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/PostManagerApplication.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/config/OpenApiConfig.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/controller/InteractionPostController.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/controller/PostManagerController.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/mapper/CommentsMapper.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/mapper/PostManagerMapper.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/mapper/ReactionsMapper.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/dto/BasicCommonAttributes.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/dto/Comments.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/dto/Reactions.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/entities/CommentsEntity.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/entities/ExtraInfoEntity.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/entities/PostEntity.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/entities/ReactionsEntity.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/web/request/CreateCommentCommonAttributes.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/web/request/CreateReactionCommonAttributes.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/web/request/PostManagerCommonAttributes.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/models/web/response/PostManagerResponse.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/repository/CommentsRepository.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/repository/PostManagerRepository.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/repository/ReactionsRepository.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/services/InteractionsPostService.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/services/PostManagerService.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/services/impl/InteractionPostServiceImpl.java
  src/post-manager-service/src/main/java/com/dialosoft/postmanager/services/impl/PostManagerServiceImpl.java
  src/post-manager-service/src/main/resources/application-docker.yml
  src/post-manager-service/src/main/resources/application-local.yml
  src/post-manager-service/src/main/resources/application.yml
  src/post-manager-service/src/test/java/com/dialosoft/postmanager/PostManagerApplicationTests.java
Labels: documentation, enhancement

#26 Bugfix: Change from OneToOne to ManyToOne relationship with Roles in UserEntity
  src/auth-service/src/main/java/com/dialosoft/auth/persistence/entity/UserEntity.java
Labels: bug

#30 Feature/management service
  docker-compose.yml
  src/gateway-service/src/main/resources/application-local.yml
  src/gateway-service/src/main/resources/application.yml
  src/management-service/Dockerfile
  src/management-service/docs/docs.go
  src/management-service/docs/swagger.json
  src/management-service/docs/swagger.yaml
  src/management-service/go.mod
  src/management-service/go.sum
  src/management-service/go.work
  src/management-service/go.work.sum
  src/management-service/main.go
  src/management-service/src/adapters/controllers/CategoryController.go
  src/management-service/src/adapters/controllers/forumController.go
  src/management-service/src/adapters/repositories/CategoryRepoImpl.go
  src/management-service/src/adapters/repositories/categoryRepo.go
  src/management-service/src/adapters/repositories/forumRepo.go
  src/management-service/src/adapters/repositories/forumRepoImpl.go
  src/management-service/src/adapters/routers/CategoryRouter.go
  src/management-service/src/adapters/routers/ForumRouter.go
  src/management-service/src/application/services/categoryService.go
  src/management-service/src/application/services/categoryServiceImpl.go
  src/management-service/src/application/services/forumService.go
  src/management-service/src/application/services/forumServiceImpl.go
  src/management-service/src/domain/entities/category.go
  src/management-service/src/domain/entities/forum.go
  src/management-service/src/domain/entities/request/createCategory.go
  src/management-service/src/domain/entities/request/createForum.go
  src/management-service/src/domain/entities/request/forumUpdates.go
  src/management-service/src/domain/entities/request/getCategoryId.go
  src/management-service/src/domain/entities/response/standard.go
  src/management-service/src/infraestructure/db/database.go
  src/management-service/src/infraestructure/registry/eureka.go
  src/management-service/src/utility/errorResponses.go
Labels: documentation, enhancement

#32 Bugfix/backend multiple requests issues
  docker-compose.yml
  src/auth-service/src/main/java/com/dialosoft/auth/AuthApplication.java
  src/auth-service/src/main/java/com/dialosoft/auth/persistence/response/RegisterResponse.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/AuthService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/TokenBlacklistService.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/RedisConfig.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/jwt/JwtUtil.java
  src/auth-service/src/main/resources/application-docker.yml
  src/gateway-service/build.gradle
  src/gateway-service/src/main/java/com/dialosoft/gateway/GatewayApplication.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/redis/RedisCacheService.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/redis/RedisCommonService.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/redis/RedisConfig.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/redis/TokenBlacklistService.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/filter/JwtAuthenticationFilter.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/filter/global/CacheResponseInRedisFilter.java
  src/gateway-service/src/main/java/com/dialosoft/gateway/config/security/util/JwtUtils.java
  src/gateway-service/src/main/resources/application-docker.yml
  src/gateway-service/src/main/resources/application.yml
  src/registry-service/src/main/resources/application.yml
Labels: bug

#33 refactor(auth-service): add validations in requests DTOs
  src/auth-service/src/main/java/com/dialosoft/auth/persistence/repository/UserRepository.java
  src/auth-service/src/main/java/com/dialosoft/auth/persistence/response/RecoverTokenResponse.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/AuthService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/RecoverService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/RefreshTokenService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/UserSecurityService.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/dto/LoginDto.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/dto/RegisterDto.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/utils/AtLeastOneField.java
  src/auth-service/src/main/java/com/dialosoft/auth/service/validator/AtLeastOneFieldValidator.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/error/GlobalExceptionHandler.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/config/error/exception/CustomTemplateException.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/controller/AuthController.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/controller/SimpleController.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/request/LoginRequest.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/request/RecoverChangePasswordRequest.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/request/RecoverRequest.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/request/RefreshTokenRequest.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/request/RegisterRequest.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/response/ErrorDTO.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/response/JwtResponseDTO.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/response/RecoverTokenResponse.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/response/RegisterResponse.java
  src/auth-service/src/main/java/com/dialosoft/auth/web/dto/response/ResponseBody.java
Labels: enhancement
